version: '2'

# Docker Compose configuration documentation can be found at https://docs.docker.com/compose/compose-file/compose-file-v2/
# MongoDB is an option to store ACLs for docker auth and and new container could be added for that

services:
  web:
    image: abiosoft/caddy:0.11.5-no-stats
    depends_on:
      - auth_server
      - docker_registry
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile
      - ./caddy/data:/root/.caddy
  auth_server:
    image: cesanta/docker_auth
    expose:
      - "5001"
    volumes:
      - ./auth_server/config:/config:ro
      - ./auth_server/ssl:/ssl
    command: /config/auth_config.yml
  docker_registry:
    image: registry:2
    expose:
      - "5000"
    volumes:
      - ./auth_server/ssl:/ssl
      - ./docker_registry/config/config.yml:/etc/docker/registry/config.yml
